<a href="https://colab.research.google.com/github/shreyash1706/Linear-Algebra-in-Code/blob/main/Lin_Alg_1_From_Scalers_to_Spaces.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is the first blog on the series:

>  `Linear Algebra for ML codified`

Index

In [ ]:
import torch
import numpy as np
import sympy as sp

#`Scalars`

Scalars are simple numbers or values in contrast to the array of multiple numbers.

Scalars can be known constants or unknown variables but both of them have a single value.

In [ ]:
scalar = torch.tensor(1.0)
scalar

tensor(1.)

#`Vectors`

In geometric terms vector is a object which has a **magnitude** and **direction** .

In programming vector is usually a array of numbers.

But both of these ideas are quite interchangeable.

The properties of vectors are they can be added with each other and multiplied by scalars.

$2*\vec{a}+3*\vec{b}=\vec{c}$

In [ ]:
vector = torch.arange(4)
vector

tensor([0, 1, 2, 3])

#`Matrices`

Matrices are 2-D arrays and most of the tabular data in ML is going to be presented in this form.

Think of them as linear transformation that converts the whole system into whole another form, we will discuss this more in the Matrix-Vector multiplication section

In [ ]:
matrix = torch.arange(8).reshape((4,2))
matrix

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

#`Tensors`

These are N-Dimensional array, which can have more than 2 axes.

These are highly useful in deep learning.

In [ ]:
tensor = torch.arange(12).reshape((2,3,2))
tensor

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

#`Basic Matrix Operations`

Matrix Addition: This is a elementwise addition of all the elements of the

In [ ]:
A = torch.arange(6).reshape((3,2))


display(sp.Matrix(A))


#this is the element wise sum of matrices
display(sp.Matrix(A+A))

Matrix([
[0, 1],
[2, 3],
[4, 5]])

Matrix([
[0,  2],
[4,  6],
[8, 10]])

Matrix Multiplication: The neccesary condition for the matrices to be multiplied it is,

$A_{mxn} * B_{nxk} = C_{mxk}$ ; The column size of A and row size of B must match.

Similiar to the elementwise addition , elementwise multiplication also exists and is called hadamard product; $A⊙B$

In [ ]:
#matrix multiplication
A = torch.arange(6).reshape((3,2))
B = torch.arange(6).reshape((2,3))

display(sp.Matrix(A))
display(sp.Matrix(B))

display(sp.Matrix(A@B))

#in torch A@B is used or torch.mm(A,B)

Matrix([
[0, 1],
[2, 3],
[4, 5]])

Matrix([
[0, 1, 2],
[3, 4, 5]])

Matrix([
[ 3,  4,  5],
[ 9, 14, 19],
[15, 24, 33]])

In [ ]:
#for hadamard product

display(sp.Matrix(A*A))

Matrix([
[ 0,  1],
[ 4,  9],
[16, 25]])

Transpose is a operation where the columns are replaces by rows and vice versa

In [ ]:
display(sp.Matrix(A.T))

Matrix([
[0, 2, 4],
[1, 3, 5]])

#`Matrix-Vector Multiplication`

Intuition of Matrix Vector multiplication , I highly suggest checking out 3B1B's linear transformation video, where he visually demostrates how a linear transformation can be visualized

Matrices can seen as linear transformation

$A = \begin{bmatrix} 2 & 5 \\ 1 & 3\end{bmatrix}$

Now the vector $\begin{bmatrix} 2 \\ 1 \end{bmatrix}$ is where the X basis vector or the vector $\begin{bmatrix} 1 \\ 0 \end{bmatrix}$ will land on this system transformed by $A$, similarly $\begin{bmatrix} 5 \\ 3 \end{bmatrix}$ is where the Y basis vector $\begin{bmatrix} 0 \\ 1 \end{bmatrix}$ will land.

Now this creates the linear transformation system in a 2x2 space or a 2-D world and this matrix or this transformation can be used to convert any $\begin{bmatrix} x \\ y \end{bmatrix}$ to a transformed plane and see where it lands.

Let's see where will the vector $\begin{bmatrix} 1 \\ 2 \end{bmatrix}$ lie after undergoing this transformation!

In [ ]:
A = torch.tensor([[2,5],[1,3]])
v = torch.tensor([1,2])

display(sp.Matrix(A))
display(sp.Matrix(v))

display(sp.Matrix(A@v))

Matrix([
[2, 5],
[1, 3]])

Matrix([
[1],
[2]])

Matrix([
[12],
[ 7]])

So we can see how the vector $\begin{bmatrix} 1 \\ 2 \end{bmatrix}$ got transformed to $\begin{bmatrix} 12 \\ 7 \end{bmatrix}$, another way of visualizing this is ->

Imagine this matrix's X axis part $\begin{bmatrix} \textbf{2} & 5 \\ \textbf{1} & 3\end{bmatrix}$ be scaled by the X component of the vector V and the Y axis part $\begin{bmatrix} 2 & \textbf{5} \\ 1 & \textbf{3}\end{bmatrix}$ scaled by the Y component of vector V

It would look like

$ 1*\begin{bmatrix} 2 \\ 1 \end{bmatrix} + 2*\begin{bmatrix} 5 \\ 3 \end{bmatrix} = \begin{bmatrix} 12 \\ 7 \end{bmatrix}$


#`System of Linear Equation`

When we have a bunch of equations they can be converted into matrix form

In [ ]:
x,y = sp.symbols('x y')

In [ ]:
eq1 = sp.Eq(2*x + 1*y, 5)
display(eq1)

Eq(2*x + y, 5)

In [ ]:
eq2 = sp.Eq(1*x -1*y,1)
display(eq2)

Eq(x - y, 1)

In [ ]:
#solving this system of equation
sol = sp.solve((eq1,eq2),(x,y))

print("solution: ",sol)

solution:  {x: 2, y: 1}


These equation were solved using subsitution

Now we convert this system of equation into matrix form

In [ ]:
A = sp.Matrix([[2,1],
          [1,-1]])
b = sp.Matrix([5,1])

print("Matrix A:")
display(A)
print("Vector b:")
display(b)

Matrix A:


Matrix([
[2,  1],
[1, -1]])

Vector b:


Matrix([
[5],
[1]])

In [ ]:
# solve Ax=b in matrix form
solution = A.LUsolve(b)
print("Solution via Ax=b:", solution)

Solution via Ax=b: Matrix([[2], [1]])


Now how was this solved in matrix form and what is LU solve will be discuss in next sections.

#`Solving Ax=b using Gaussian Elimination`

We will use the Reduced Row Echelon Form to solve this. (How the libararies do it!)

In [ ]:
A = np.random.randint(1, 10, (3, 3))
while np.linalg.det(A) == 0:  # regenerate if singular
    A = np.random.randint(1, 10, (3, 3))

# Random 3x1 vector
b = np.random.randint(1, 10, (3, 1))

print("A =\n", A)
print("b =\n", b)

A =
 [[3 9 3]
 [8 4 6]
 [4 5 2]]
b =
 [[1]
 [4]
 [2]]


In [ ]:
#To Solve Ax=b

def rref(A, b):


SyntaxError: incomplete input (ipython-input-1915319521.py, line 3)

#`Eigen Value and Eigen Vectors`

These are surprisingly not just some terms to use for applications but have pretty interesting explanations

$ A\vec{v} = λ\vec{v}$

*λ is such a eigen value and $\vec{v}$ is the corresponding eigen vector*

$A$ is a linear transformation matrix and it usually relocates the vectors in
$ℝ^n$ and knock them off from their span.

But the eigen vectors are the special vectors whose orientation remains the same and the are just scaled by the scalar value of 'eigen value'.


This seems a bit confusing because $A\vec{v}$ is matrix vector multiplication and $λ\vec{v}$ is scalar vector multiplication

So to convert the scalar-vector mul into a matrix we multiple it by $I^n$ the identity matrix

Let's see it in action